"""Compile the vault into brain/web/data/graph.js (window.BRAIN).

Refuses to write if validation fails.
Usage: python brain/scripts/build_graph.py
"""
import datetime
import json
import os
import sys
from collections import Counter

import vaultlib

OUT = os.path.normpath(os.path.join(
    os.path.dirname(__file__), "..", "web", "data", "graph.js"))


def main():
    notes, edges, errors, _warnings = vaultlib.load_vault()
    if errors:
        print("Vault has %d error(s) — run validate_vault.py. Not writing." % len(errors))
        for e in errors[:20]:
            print("  ! " + e)
        sys.exit(1)

    nodes = []
    for n in sorted(notes.values(), key=lambda x: x["id"]):
        nodes.append({
            "id": n["id"], "title": n["title"], "type": n["type"],
            "category": n["category"], "folder": n["folder"],
            "confidence": n["confidence"], "degree": n["degree"],
            "tags": n["tags"], "source": n["source"], "body": n["body"],
        })
    links = [{"source": a, "target": b, "rel": r} for a, b, r in edges]

    meta = {
        "built": datetime.datetime.now().isoformat(timespec="seconds"),
        "nodes": len(nodes),
        "links": len(links),
        "types": dict(Counter(n["type"] for n in nodes)),
        "categories": dict(Counter(n["category"] for n in nodes)),
    }

    payload = json.dumps({"meta": meta, "nodes": nodes, "links": links},
                         ensure_ascii=False, separators=(",", ":"))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// GENERATED by brain/scripts/build_graph.py — do not edit\n")
        f.write("window.BRAIN = ")
        f.write(payload)
        f.write(";\n")
    print("wrote %s  (%d nodes, %d links, %.1f KB)" % (
        OUT, len(nodes), len(links), os.path.getsize(OUT) / 1024.0))


if __name__ == "__main__":
    main()
